window.MathJax = {
    loader: { load: ['[tex]/tagformat', '[tex]/configmacros', '[tex]/physics'] },
    tex: {
        // packages included
        packages: { '[+]': ['tagformat', 'configmacros', 'physics'] },
        // inline math mode delimiters
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        // display math mode delimiters
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
        // use \$ to escape the dollar sign
        processEscapes: true,
        // process \begin{xxx}...\end{xxx} outside of math mode
        processEnvironments: true,
        // process \ref{...} outside of math mode
        processRefs: true,
        // pattern for recognizing numbers
        digits: /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\.[0-9]*)?|\.[0-9]+)/,
        // tag options
        tags: 'ams',
        tagSide: 'right',
        tagIndent: '2em',
        tagformat: {
            number: (n) => n.toString(),
            tag: (tag) => '(' + tag + ')',
            id: (id) => 'mjx-eqn:' + id.replace(/\s/g, '_'),
            url: (id, base) => base + '#' + encodeURIComponent(id)
        },
        // use label name rather than tag for ids
        useLabelIds: true,
        //showProcessingMessages: true,
        // macros
        macros: {
            // size control of tilde, bar and hat,
            wave: ['{\\widetilde{#1}}', 1],
            bar: ['{\\overline{#1}}', 1],
            hat: ['{\\widehat{#1}}', 1],
            geq: '{\\geqslant}',
            leq: '{\\leqslant}',
            // to suppress the numbering in align,
            nn: '{\\nonumber}',
            // colored text,
            red: ['{\\textcolor{red}{#1}}', 1],
            orange: ['{\\textcolor{orange}{#1}}', 1],
            blue: ['{\\textcolor{blue}{#1}}', 1],
            purple: ['{\\textcolor{purple}{#1}}', 1],
            pink: ['{\\textcolor{pink}{#1}}', 1],
            notethat: ['{\\textcolor{red}{#1}}', 1],
            impliesthat: '{$\\implies$}',
            // shortcuts used in CFT,
            // vacuum,
            vac: '{\\ket{0}}',
            // vacuum expectation value,
            vev: ['{\\langle #1 \\rangle}', 1],
            // field operator,
            op: '{\\cO}',
            // shadow operator,
            opshadow: '{\\wave{\\op}}',
            fshadow: '{\\wave{\\f}}',
            // composite operator,
            opcomposite: '{\\op_{e}}',
            // singlet structure,
            singletstructure: '{r=1}',
            // Gramian matrix,
            gram: '{G}',
            // stripped four-point functions,
            fourpt: '{\\cG}',
            // stripped blocks,
            blockstripped: '{g}',
            // blocks with kinematical factors,
            blockdressed: '{G}',
            // stripped partial waves,
            CPWstripped: '{\\psi}',
            // partial waves with kinematical factors,
            CPWdressed: '{\\Psi}',
            // highest weight module,
            rep: ['{\\cV_{#1}}', 1],
            // unitary module,
            urep: ['{\\cE_{#1}}', 1],
            // celestial sphere,
            csphere: '{$\\mathcal{CS}^2$}',
            // celestial ring,
            cring: '{$\\mathcal{CS}^1$}',
            // transverse momentum,
            pT: '{p_{\\perp}}' ,
            // transverse direction,
            xT: '{x_{\\perp}}' ,
            // unit fm,
            fm: '{\\operatorname{fm}}',
            // unit Gev,
            GeV: ['{\\operatorname{GeV}^{#1}}', 1],
            // in state,
            ain: '{a_{\\operatorname{in}}}',
            // out state,
            aout: '{a_{\\operatorname{out}}}',
            // vector p,
            vp: '{\\vec{p}}',
            // vector x,
            vx: '{\\vec{x}}',
            // complex coordinates,
            hb: '{\\bar{h}}',
            wbar: '{\\bar{w}}',
            zbar: '{\\bar{z}}',
            Tbar: '{\\bar{T}}',
            Lbar: '{\\bar{L}}',
            psib: '{\\bar{\\psi}}',
            // Dirac conjugate,
            Vfuture: '{\\bar{V}_{+}}',
            Vpast: '{\\bar{V}_{-}}',
            Vcausal: '{\\bar{V}_{\\pm}}',
            // Special functions,
            rising: ['{#1^{\\overline{#2}}\\,}', 2],
            // Rising factorials ,
            falling: ['{#1^{\\underline{#2}}\\,}', 2],
            // Falling factorials,
            // Hypergeometric functions,
            Faa: '{{}_{1}F_{1}}',
            Fab: '{{}_{1}F_{2}}',
            Fba: '{{}_{2}F_{1}}',
            Fcb: '{{}_{3}F_{2}}',
            // miscellaneous,
            // discontinuity,
            disc: '{\\operatorname{Disc}}',
            // phantom equal at the beginning,
            peq: '{\\phantom{=}}',
            // linear span,
            vspan: ['{\\operatorname{span}\\set{ #1 }}', 1],
            // sets,
            set: ['{\\left\\{ #1 \\right\\}}', 1],
            // case,
            case: ['{\\begin{cases} #1 \\end{cases}}', 1],
            // left hand side,
            lhs: '{\\text{l.h.s}}',
            // right hand side,
            rhs: '{\\text{r.h.s}}',
            // to control spacings in integral,
            intt: ['{\\int #1\\,}', 1],
            // to control spacings in integral,
            inttt: ['{\\int_{#2} #1\\,}', 2],
            // half,
            half: '{\\frac{1}{2}}',
            // dot,
            '.': '{\\cdot}',
            // times,
            x: '{\\times}',
            // tensor product,
            ox: '{\\otimes}',
            // direct sum,
            os: '{\\oplus}',
            // wedge product,
            w: '{\\wedge}',
            // infinity,
            inf: '{\\infty}',
            oo: '{\\infty}',
            // partial,
            p: '{\\partial}',
            // grad,
            n: '{\\nabla}',
            // Sign function,
            sign: '{\\operatorname{sgn}}',
            // diagonal matrix,
            diag: ['{\\operatorname{diag}\\left( #1 \\right)}', 1],
            // Euler-Lagrangian operator,
            EL: '{\\operatorname{EL}}',
            // overset: ['{A}{B}{A over B}', 2],
            // underset: ['{A}{B}{A under B}', 2],
            // substack: ['{A}', 1],
            // as multiline subscripts,
            // algebras,
            // inverse limit,
            inverselimit: '{\\varprojlim}' ,
            // direct limit,
            directlimit: '{\\varinjlim}' ,
            // image,
            im: '{\\operatorname{im}}' ,
            // coimage,
            coim: '{\\operatorname{coim}}' ,
            // cokernel,
            coker: '{\\operatorname{coker}}' ,
            // operator index,
            opindex: '{\\operatorname{index}}',
            // spectrum,
            spec: '{\\operatorname{spec}}' ,
            // diffeomorphism,
            Diff: '{\\operatorname{Diff}}' ,
            // hom set,
            Hom: '{\\operatorname{Hom}}' ,
            // automorphism,
            Aut: '{\\operatorname{Aut}}' ,
            // endomorphism,
            End: '{\\operatorname{End}}' ,
            // outer automorphism,
            Out: '{\\operatorname{Out}}' ,
            // inner automorphism,
            Inn: '{\\operatorname{Inn}}' ,
            // identity,
            id: '{\\operatorname{id}}' ,
            // adjoint action of Lie algebra,
            ad: '{\\operatorname{ad}}' ,
            // adjoint action of Lie group,
            Ad: '{\\operatorname{Ad}}' ,
            // dimension,
            // dim: '{\\operatorname{dim}}' ,
            // codimension,
            codim: '{\\operatorname{codim}}' ,
            // volume,
            vol: '{\\operatorname{vol}}' ,
            // induction,
            Ind: '{\\operatorname{Ind}}' ,
            // radical of algebra,
            rad: '{\\operatorname{rad}}' ,
            // dual space,
            dual: ['{{#1}^\\vee}', 1],
            // inverse,
            '-': '{{-1}}' ,
            // Hermitian conjugate,
            '+': '{\\dagger}',
            // Hilbert space,
            H: '{\\mathcal{H}}',
            // Moduli spaces,
            M: '{\\mathcal{M}}',
            // categories,
            setcat: '{\\operatorname{Set}}',
            veccat: '{\\operatorname{Vec}}',
            catcat: '{\\operatorname{Cat}}',
            // vector spaces,
            Uvec: '{\\mathbb{U}}',
            Vvec: '{\\mathbb{V}}',
            Wvec: '{\\mathbb{W}}',
            // Greek letters,
            a: '{\\alpha}',
            b: '{\\beta}',
            c: '{\\chi}',
            d: '{\\delta}',
            D: '{\\Delta}',
            e: '{\\epsilon}',
            ve: '{\\varepsilon}',
            g: '{\\gamma}',
            G: '{\\Gamma}',
            k: '{\\kappa}',
            l: '{\\lambda}',
            lm: '{\\lambda}',
            L: '{\\Lambda}',
            f: '{\\phi}',
            vf: '{\\varphi}',
            r: '{\\rho}',
            s: '{\\sigma}',
            S: '{\\Sigma}',
            o: '{\\omega}',
            O: '{\\Omega}',
            th: '{\\theta}',
            Th: '{\\Theta}',
            t: '{\\tau}',
            z: '{\\zeta}',
            // number systems,
            // reals,
            R: '{\\mathbb{R}}',
            Rnot: '{\\mathbb{R}^{\\neq 0}}',
            Rneq: '{\\mathbb{R}^{\\neq 0}}',
            Rgeq: '{\\mathbb{R}^{\\geqslant 0}}',
            Rpositive: '{\\mathbb{R}^{> 0}}',
            Rleq: '{\\mathbb{R}^{\\leqslant 0}}',
            Rnegative: '{\\mathbb{R}^{< 0}}',
            // integers,
            Z: '{\\mathbb{Z}}',
            Znot: '{\\mathbb{Z}^{\\geqslant 0}}',
            Zneq: '{\\mathbb{Z}^{\\neq 0}}',
            N: '{\\mathbb{N}}',
            Zgeq: '{\\mathbb{Z}^{\\geqslant 0}}',
            Zpositive: '{\\mathbb{Z}^{> 0}}',
            Zleq: '{\\mathbb{Z}^{\\leqslant 0}}',
            Znegative: '{\\mathbb{Z}^{< 0}}',
            // rationals,
            Q: '{\\mathbb{Q}}',
            Qnot: '{\\mathbb{Q}^{\\geqslant 0}}',
            Qneq: '{\\mathbb{Q}^{\\neq 0}}',
            Qgeq: '{\\mathbb{Q}^{\\geqslant 0}}',
            Qpositive: '{\\mathbb{Q}^{> 0}}',
            Qleq: '{\\mathbb{Q}^{\\leqslant 0}}',
            Qnegative: '{\\mathbb{Q}^{< 0}}',
            // complex numbers,
            C: '{\\mathbb{C}}',
            Cneq: '{\\mathbb{C}^{\\neq 0}}',
            Cnot: '{\\mathbb{C}^{\\neq 0}}',
            // projective,
            P: '{\\mathbb{P}}',
            // p-adic numbers,
            Qp: '{\\mathbb{Q}_{p}}',
            Zp: '{\\mathbb{Z}_{p\\text{-adic}}}',
            Up: '{\\mathbb{U}_{p}}',
            // Lie algebras and groups,
            spin: '{\\operatorname{Spin}}',
            lie: ['{\\mathfrak{#1}}', 1],
            glie: '{\\mathfrak{g}}',
            gllie: '{\\mathfrak{gl}}',
            sllie: '{\\mathfrak{sl}}',
            isllie: '{\\mathfrak{isl}}',
            ulie: '{\\mathfrak{u}}',
            sulie: '{\\mathfrak{su}}',
            olie: '{\\mathfrak{o}}',
            solie: '{\\mathfrak{so}}',
            isolie: '{\\mathfrak{iso}}',
            splie: '{\\mathfrak{sp}}',
            // nilpotent,
            nlie: '{\\mathfrak{n}}',
            // parabolic,
            plie: '{\\mathfrak{p}}',
            // Borel,
            blie: '{\\mathfrak{b}}',
            // Cartan,
            hlie: '{\\mathfrak{h}}',
            // compact,
            klie: '{\\mathfrak{k}}',
            // calligraphic capitals,
            cA: '{\\mathcal{A}}',
            cB: '{\\mathcal{B}}',
            cC: '{\\mathcal{C}}',
            cD: '{\\mathcal{D}}',
            cE: '{\\mathcal{E}}',
            cF: '{\\mathcal{F}}',
            cG: '{\\mathcal{G}}',
            cH: '{\\mathcal{H}}',
            cI: '{\\mathcal{I}}',
            cJ: '{\\mathcal{J}}',
            cK: '{\\mathcal{K}}',
            cL: '{\\mathcal{L}}',
            cM: '{\\mathcal{M}}',
            cN: '{\\mathcal{N}}',
            cO: '{\\mathcal{O}}',
            cP: '{\\mathcal{P}}',
            cQ: '{\\mathcal{Q}}',
            cR: '{\\mathcal{R}}',
            cS: '{\\mathcal{S}}',
            cT: '{\\mathcal{T}}',
            cU: '{\\mathcal{U}}',
            cV: '{\\mathcal{V}}',
            cW: '{\\mathcal{W}}',
            cX: '{\\mathcal{X}}',
            cY: '{\\mathcal{Y}}',
            cZ: '{\\mathcal{Z}}',
        },
        enviroments: {
            //testenviroment: ['\\left\\{', '\\right\\}']
        },
    },
    // package physics options
    physics: {
        italicdiff: false,
        arrowdel: false
    },
    options: {
        ignoreHtmlClass: '.',
        processHtmlClass: 'arithmatex'
    }
};