window.MathJax = {
    loader: {
        load: ['[tex]/tagformat', '[tex]/configmacros', '[tex]/physics']
    },
    tex: {
        // packages included
        packages: { '[+]': ['tagformat', 'configmacros', 'physics'] },
        // inline math mode delimiters
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        // display math mode delimiters
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
        // use \$ to escape the dollar sign
        processEscapes: true,
        // process \begin{xxx}...\end{xxx} outside of math mode
        processEnvironments: true,
        // process \ref{...} outside of math mode
        processRefs: true,
        // pattern for recognizing numbers
        digits: /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\.[0-9]*)?|\.[0-9]+)/,
        // tag options
        tags: 'ams',
        tagSide: 'right',
        tagIndent: '2em',
        tagformat: {
            number: (n) => n.toString(),
            tag: (tag) => '(' + tag + ')',
            id: (id) => 'mjx-eqn:' + id.replace(/\s/g, '_'),
            url: (id, base) => base + '#' + encodeURIComponent(id)
        },
        useLabelIds: true,
        // macros
        macros: {
            // DONT overwrite this part
            ppair: ['{\\left( #1 \\right)}', 1],
            // DONT overwrite this part
            //
            //
            // Automatically transformed from LaTeX
            //
            //
            // customized physics package
            ppair: ['{\\pqty{#1}}', 1],
            bpair: ['{\\bqty{#1}}', 1],
            vpair: ['{\\vqty{#1}}', 1],
            Bpair: ['{\\Bqty{#1}}', 1],
            //
            // pmat is the \\paulimat in the physics package,
            pmat: ['{\\pmqty{#1}}', 1],
            Pmat: ['{\\Pmqty{#1}}', 1],
            bmat: ['{\\bmqty{#1}}', 1],
            vmat: ['{\\vmqty{#1}}', 1],
            //
            poisson: ['{\\poissonbracket{#1}{#2}}', 2],
            matrixele: ['{\\matrixel{#1}{#2}{#3}}', 3],
            ele: ['{\\matrixel{#1}{#2}{#3}}', 3],
            qiff: '{\\qq{iff}}',
            matdet: ['{\\matrixdeterminant{#1}}', 1],
            smatdet: ['{\\smallmatrixdeterminant{#1}}', 1] ,
            //
            //
            // size control of tilde, bar and hat,
            wave: ['{\\widetilde{#1}}', 1],
            bar: ['{\\overline{#1}}', 1],
            hat: ['{\\widehat{#1}}', 1],
            geq: '{\\geqslant}',
            leq: '{\\leqslant}',
            // case,
            case: ['{\\begin{cases} #1 \\end{cases}}', 1],
            // to suppress the numbering in align,
            nn: '{\\nonumber}',
            // text,
            red: ['{\\textcolor{red}{#1}}', 1],
            orange: ['{\\textcolor{orange}{#1}}', 1],
            blue: ['{\\textcolor{blue}{#1}}', 1],
            purple: ['{\\textcolor{purple}{#1}}', 1],
            pink: ['{\\textcolor{pink}{#1}}', 1],
            notethat: ['{\\textcolor{red}{#1}}', 1],
            impliesthat: '{$\\implies$}',
            // phantom equal at the beginning,
            peq: '{\\phantom{=}}',
            // left hand side,
            lhs: '{\\text{l.h.s}}',
            // right hand side,
            rhs: '{\\text{r.h.s}}',
            // constant ,
            const: '{\\operatorname{const}}',
            // shortcuts used in CFT,
            // vacuum,
            vac: '{\\ket{0}}',
            // vacuum expectation value,
            vev: ['{\\langle #1 \\rangle}', 1],
            // field operator,
            op: '{\\cO}',
            // shadow operator,
            opshadow: '{\\wave{\\op}}',
            fshadow: '{\\wave{\\f}}',
            // composite operator,
            opcomposite: '{\\op_{e}}',
            // singlet structure,
            singletstructure: '{r=1}',
            // Gramian matrix,
            gram: '{G}',
            // stripped four-point functions,
            fourpt: '{\\cG}',
            // stripped blocks,
            blockstripped: '{g}',
            // blocks with kinematical factors,
            blockdressed: '{G}',
            // stripped partial waves,
            CPWstripped: '{\\psi}',
            // partial waves with kinematical factors,
            CPWdressed: '{\\Psi}',
            // highest weight module,
            rep: ['{\\cV_{#1}}', 1],
            // unitary module,
            urep: ['{\\cE_{#1}}', 1],
            urepdiscrete: ['{\\cD_{#1}}', 1],
            // unitary dual,
            udual: ['{\\wave{#1}}', 1],
            // transverse momentum,
            pT: '{p_{\\perp}}',
            // transverse direction,
            xT: '{x_{\\perp}}',
            // in state,
            instate: ['{#1_{\\operatorname{in}}}', 1],
            // out state,
            outstate: ['{#1_{\\operatorname{out}}}', 1],
            // discontinuity,
            disc: '{\\operatorname{Disc}}',
            // unit fm,
            fm: '{\\operatorname{fm}}',
            // unit Gev,
            GeV: ['{\\operatorname{GeV}^{#1}}', 1],
            // vector p,
            vp: '{\\vec{p}}',
            // vector x,
            vx: '{\\vec{x}}',
            // complex coordinates,
            hb: '{\\bar{h}}',
            wbar: '{\\bar{w}}',
            zbar: '{\\bar{z}}',
            Tbar: '{\\bar{T}}',
            Lbar: '{\\bar{L}}',
            psib: '{\\bar{\\psi}}',
            // Dirac conjugate,
            Vfuture: '{\\bar{V}_{+}}',
            Vpast: '{\\bar{V}_{-}}',
            Vcausal: '{\\bar{V}_{\\pm}}',
            // Hypergeometric functions,
            Faa: '{{}_{1}F_{1}}',
            Fab: '{{}_{1}F_{2}}',
            Fba: '{{}_{2}F_{1}}',
            Fcb: '{{}_{3}F_{2}}',
            // miscellaneous,
            // to control spacings in integral,
            intt: ['{\\int #1\\,}', 1],
            // to control spacings in integral,
            inttt: ['{\\int_{#2} #1\\,}', 2],
            // to control spacings in integral,
            intrange: ['{\\int_{#2}^{#3} #1\\,}', 3],
            // half,
            half: '{\\frac{1}{2}}',
            // times,
            x: '{\\times}',
            // tensor product,
            ox: '{\\otimes}',
            // direct sum,
            os: '{\\oplus}',
            // wedge product,
            w: '{\\wedge}',
            // infinity,
            inf: '{\\infty}',
            oo: '{\\infty}',
            // partial,
            p: '{\\partial}',
            // grad,
            n: '{\\nabla}',
            // Sign function,
            sign: '{\\operatorname{sgn}}',
            // diagonal matrix,
            diag: ['{\\operatorname{diag}\\left( #1 \\right)}', 1],
            // Euler-Lagrangian operator,
            EL: '{\\operatorname{EL}}',
            // linear span,
            vspan: ['{\\operatorname{span}\\{ #1 \\}}', 1],
            // sets,
            set: ['{\\{ #1 \\}}', 1],
            // mod,
            modd: ['{\\, \\operatorname{mod} #1 }', 1],
            // algebras,
            // inverse limit,
            inverselimit: '{\\varprojlim}',
            // direct limit,
            directlimit: '{\\varinjlim}',
            // image,
            im: '{\\operatorname{im}}',
            // coimage,
            coim: '{\\operatorname{coim}}',
            // cokernel,
            coker: '{\\operatorname{coker}}',
            // operator index,
            opindex: '{\\operatorname{index}}',
            // spectrum,
            spec: '{\\operatorname{spec}}',
            // diffeomorphism,
            Diff: '{\\operatorname{Diff}}',
            // hom set,
            Hom: '{\\operatorname{Hom}}',
            // automorphism,
            Aut: '{\\operatorname{Aut}}',
            // endomorphism,
            End: '{\\operatorname{End}}',
            // outer automorphism,
            Out: '{\\operatorname{Out}}',
            // inner automorphism,
            Inn: '{\\operatorname{Inn}}',
            // identity,
            id: '{\\operatorname{id}}',
            // adjoint action of Lie algebra,
            ad: '{\\operatorname{ad}}',
            // adjoint action of Lie group,
            Ad: '{\\operatorname{Ad}}',
            // dimension,
            // dim: '{\\operatorname{dim}}' ,
            // codimension,
            codim: '{\\operatorname{codim}}',
            // volume,
            vol: '{\\operatorname{vol}}',
            // induction,
            ind: '{\\operatorname{Ind}}',
            // restriction,
            res: '{\\operatorname{Res}}',
            // radical of algebra,
            rad: '{\\operatorname{rad}}',
            // dual space,
            dual: ['{{#1}^\\vee}', 1],
            // Hilbert space,
            H: '{\\mathcal{H}}',
            // inner product,
            innerproductmath: ['{(#1,#2)}', 2],
            innerproductphy: ['{#1 \\cdot #2}', 2],
            // Moduli spaces,
            M: '{\\mathcal{M}}',
            // cohomology,
            ext: '{\\operatorname{Ext}}',
            tor: '{\\operatorname{Tor}}',
            // categories,
            setcat: '{\\operatorname{Set}}',
            veccat: '{\\operatorname{Vec}}',
            catcat: '{\\operatorname{Cat}}',
            catA: '{\\mathcal{A}}',
            catB: '{\\mathcal{B}}',
            catC: '{\\mathcal{C}}',
            catD: '{\\mathcal{D}}',
            catE: '{\\mathcal{E}}',
            catF: '{\\mathcal{F}}',
            catG: '{\\mathcal{G}}',
            // vector spaces,
            Uvec: '{\\mathbb{U}}',
            Vvec: '{\\mathbb{V}}',
            Wvec: '{\\mathbb{W}}',
            // Greek letters,
            a: '{\\alpha}',
            // ,
            b: '{\\beta}',
            // ,
            c: '{\\chi}',
            // ,
            d: '{\\delta}',
            // ,
            D: '{\\Delta}',
            // ,
            e: '{\\epsilon}',
            // ,
            ve: '{\\varepsilon}',
            // ,
            g: '{\\gamma}',
            // ,
            G: '{\\Gamma}',
            // ,
            k: '{\\kappa}',
            // ,
            l: '{\\lambda}',
            // ,
            L: '{\\Lambda}',
            // ,
            lm: '{\\lambda}',
            // ,
            f: '{\\phi}',
            // ,
            vf: '{\\varphi}',
            // ,
            r: '{\\rho}',
            // ,
            s: '{\\sigma}',
            // ,
            S: '{\\Sigma}',
            // ,
            o: '{\\omega}',
            // ,
            O: '{\\Omega}',
            // ,
            t: '{\\tau}',
            // ,
            th: '{\\theta}',
            // ,
            Th: '{\\Theta}',
            // ,
            z: '{\\zeta}',
            // number systems,
            // reals,
            R: '{\\mathbb{R}}',
            RR: '{\\mathbb{R}}',
            Rnot: '{\\mathbb{R}^{\\neq 0}}',
            Rneq: '{\\mathbb{R}^{\\neq 0}}',
            Rgeq: '{\\mathbb{R}^{\\geqslant 0}}',
            Rpositive: '{\\mathbb{R}^{> 0}}',
            Rleq: '{\\mathbb{R}^{\\leqslant 0}}',
            Rnegative: '{\\mathbb{R}^{< 0}}',
            // integers,
            Z: '{\\mathbb{Z}}',
            ZZ: '{\\mathbb{Z}}',
            N: '{\\mathbb{N}}',
            NN: '{\\mathbb{N}}',
            Znot: '{\\mathbb{Z}^{\\geqslant 0}}',
            Zneq: '{\\mathbb{Z}^{\\neq 0}}',
            Zgeq: '{\\mathbb{Z}^{\\geqslant 0}}',
            Zpositive: '{\\mathbb{Z}^{> 0}}',
            Zleq: '{\\mathbb{Z}^{\\leqslant 0}}',
            Znegative: '{\\mathbb{Z}^{< 0}}',
            // rationals,
            Q: '{\\mathbb{Q}}',
            QQ: '{\\mathbb{Q}}',
            Qnot: '{\\mathbb{Q}^{\\geqslant 0}}',
            Qneq: '{\\mathbb{Q}^{\\neq 0}}',
            Qgeq: '{\\mathbb{Q}^{\\geqslant 0}}',
            Qpositive: '{\\mathbb{Q}^{> 0}}',
            Qleq: '{\\mathbb{Q}^{\\leqslant 0}}',
            Qnegative: '{\\mathbb{Q}^{< 0}}',
            // complex numbers,
            C: '{\\mathbb{C}}',
            CC: '{\\mathbb{CC}}',
            Cneq: '{\\mathbb{C}^{\\neq 0}}',
            Cnot: '{\\mathbb{C}^{\\neq 0}}',
            // projective,
            P: '{\\mathbb{P}}',
            CP: '{\\mathbb{CP}}',
            RP: '{\\mathbb{RP}}',
            // p-adic numbers,
            Qp: '{\\mathbb{Q}_{p}}',
            Zp: '{\\mathbb{Z}_{p}}',
            Up: '{\\mathbb{U}_{p}}',
            // Lie algebras and groups,
            spin: '{\\operatorname{Spin}}',
            lie: ['{\\mathfrak{#1}}', 1],
            glie: '{\\mathfrak{g}}',
            gllie: '{\\mathfrak{gl}}',
            sllie: '{\\mathfrak{sl}}',
            isllie: '{\\mathfrak{isl}}',
            ulie: '{\\mathfrak{u}}',
            sulie: '{\\mathfrak{su}}',
            olie: '{\\mathfrak{o}}',
            solie: '{\\mathfrak{so}}',
            isolie: '{\\mathfrak{iso}}',
            splie: '{\\mathfrak{sp}}',
            // nilpotent,
            nlie: '{\\mathfrak{n}}',
            // parabolic,
            plie: '{\\mathfrak{p}}',
            // Borel,
            blie: '{\\mathfrak{b}}',
            // Cartan,
            hlie: '{\\mathfrak{h}}',
            // compact,
            klie: '{\\mathfrak{k}}',
            // calligraphic capitals,
            cA: '{\\mathcal{A}}',
            cB: '{\\mathcal{B}}',
            cC: '{\\mathcal{C}}',
            cD: '{\\mathcal{D}}',
            cE: '{\\mathcal{E}}',
            cF: '{\\mathcal{F}}',
            cG: '{\\mathcal{G}}',
            cH: '{\\mathcal{H}}',
            cI: '{\\mathcal{I}}',
            cJ: '{\\mathcal{J}}',
            cK: '{\\mathcal{K}}',
            cL: '{\\mathcal{L}}',
            cM: '{\\mathcal{M}}',
            cN: '{\\mathcal{N}}',
            cO: '{\\mathcal{O}}',
            cP: '{\\mathcal{P}}',
            cQ: '{\\mathcal{Q}}',
            cR: '{\\mathcal{R}}',
            cS: '{\\mathcal{S}}',
            cT: '{\\mathcal{T}}',
            cU: '{\\mathcal{U}}',
            cV: '{\\mathcal{V}}',
            cW: '{\\mathcal{W}}',
            cX: '{\\mathcal{X}}',
            cY: '{\\mathcal{Y}}',
            cZ: '{\\mathcal{Z}}'
        },
        environments: {
        },
    },
    showProcessingMessages: true,
    // package physics options
    physics: {
        italicdiff: false,
        arrowdel: false
    },
    options: {
        ignoreHtmlClass: '.',
        processHtmlClass: 'arithmatex'
    }
};

