site_name: Sora
site_description: Sora
site_url: https://yuriever.github.io/


nav:
  - Home: index.md
  - Triangulated Reality: 
    - Index: subdir_symbolic/index_symbolic.md
    - Mathematica: subdir_symbolic/mma/index_mma.md
    - SageMath: subdir_symbolic/sagemath/index_sagemath.md
  - Archieve: subdir_archieve/index_archieve.md
  - Light Novel: 
    - Index: subdir_lightnovel/index_lightnovel.md 
    - Celestial CFT: subdir_lightnovel/celestial_CFT/celestial_CFT.md
  - Ochiba: subdir_ochiba/index_ochiba.md


# 主题设定
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide
  palette:
    primary: deep purple
    accent: blue
  logo: img/logo1.png
  favicon: img/logo1.png


# 关闭页底的"made with material"
extra:
  generator: false


# css文件
extra_css:
  - css/extra.css


# 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - extra
  - tables

      

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
- js/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
